pollster/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

pollster/pollster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

pollster/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes       = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollster/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    return render(request, 'polls/index.html', {'latest_question_list': latest_question_list})

#show a specific question choices
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question not Found")
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'The selected choice is invalid.'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        #Always return an HttpResponseRedirect after sucessfully dealing
        #with POST data. This prevents data form being duplicated if a user
        # hits the back button
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

pollster/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Pollster {% block title %}{% endblock %}</title>
</head>
<body>
    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="col-md-6 m-auto">
            {% block content %}{% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

pollster/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
<div class="container">
    <a class="navbar-brand" href="/">Pollster</a>
</div>
</nav>

pollster/templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back to Polls</a>
<h1 class="text-center mb-3">{{question.question_text}}</h1>

{%if error_message %}
<p class="alert alert-danger">
    <strong>{{error_message}}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <div class="form-check border border-primary rounded mb-2">
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}"><h3>{{choice.choice_text}}</h3></label>
        </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4">
</form>

{% endblock content %}

pollster/templates/polls/index.html
{% extends 'base.html' %}

{%block title %}Polls{% endblock title %}

{% block content %}
    <h1 class="text-center mb-3">Poll Questions</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
        <div class="card mb-3">
            <div class="card-body">
                <p class="lead">
                    {{ question.question_text }}
                </p>
                <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">See Results</a>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p>No polls available at the moment</p>
    {% endif %}
{% endblock content %}

pollster/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mb-3">{{question.question_text}}</h1>

{%if error_message %}
<p class="alert alert-danger">
    <strong>{{error_message}}</strong>
</p>
{% endif %}

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
        <li class="list-group-item">
            {{choice.choice_text}} <span class="badge bg-success float-right">
                {{choice.votes}} vote{{choices.votes | pluralize}} <!-- se tiver mais q um faz a pluralizacao da palavra -->
            </span>
        </li>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4">
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back to Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote Again</a>
{% endblock content %}